---
id: Memcache
name: Memcache
full: Memcache client library
description: A library for accessing a memcache installation.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Memcache
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 1.1.0
state:
  release: alpha
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7 || ^8
    composer:
      horde/exception: ^3
    ext:
      hash: '*'
  optional:
    ext:
      memcache: ^2
      memcached: '*'
  dev:
    composer:
      horde/test: ^3
      horde/log: ^3
